add qt deps' build script for NCHC machine
solvcon/devenv pull request #155
Opened 2023-04-10 13:19 UTC by terrychan999

To address the issue of outdated packages on NCHC's Taiwan-1, I have added some build scripts for the Qt dependencies.

One of the scripts is `XCB`, which includes several `XCB`-related packages within a single script. However, I am not entirely certain if this approach is appropriate. Thanks for reviewing my changes.

2023-04-11 01:51 UTC, yungyuc requested changes
@chestercheng Could you please also take a look?

2023-04-11 01:51 UTC, yungyuc commented on scripts/build.d/xcb
> +
@terrychan999 Could you add a section of comments to summarize the packages included in this script?

2023-04-11 23:21 UTC, yungyuc commented on scripts/build.d/xcb
> +
Thanks.  In the comment block please describe why keeping the 9 packages in a script is a good idea.  Then I am good with it.

2023-04-12 10:28 UTC, chestercheng commented
LGTM
The dependency issues were troublesome, so thank you for the contribution of the updates in this PR.

2023-04-12 10:28 UTC, chestercheng approved these changes

2023-04-12 10:49 UTC, merged