Update github actions macos version
solvcon/devenv pull request #159
Opened 2023-09-19 00:11 UTC by j8xixo12

Since `macos-10-15` is outdated, therefore I have updated the macOS version of GitHub actions `Unittest - shunit2` from `macos-10-15` to `macos-latest`.

2023-09-19 05:10 UTC, yungyuc requested changes
Thanks, @j8xixo12 .  Could we use a minor revision?

2023-09-20 00:20 UTC, j8xixo12 commented on .github/workflows/shunit2_runner.yml
> +        os: [ubuntu-20.04, macos-latest]
According to https://github.com/actions/runner-images#image-releases `macos-latest` now is `macos-12`, therefore I have updated version number with `macos-12` in https://github.com/solvcon/devenv/pull/159/commits/bc0075d1b500e1517cb812eb949e3d35b2b1a6b6

2023-09-20 00:23 UTC, yungyuc commented on .github/workflows/shunit2_runner.yml
> +        os: [ubuntu-20.04, macos-latest]
Thanks a lot.

2023-09-20 00:23 UTC, yungyuc approved these changes

2023-09-20 00:23 UTC, merged

2023-09-20 00:23 UTC, yungyuc commented
Fixes #157