Align Qt version
solvcon/devenv pull request #170
Opened 2024-09-13 04:07 UTC by dragonwu0919

This PR updates the default Qt version in the build script to 6.6.3. Specifically, line 44 of the file scripts/build.d/qt was modified from:
Related to #169

2024-09-13 11:26 UTC, yungyuc commented
@xingularity could you please help review the PR?

2025-01-12 11:23 UTC, xingularity commented
Hi @dragonwu0919 

We have recently upgraded the Qt version to 6.8.1, could you change the version to 6.8.1?

2025-01-12 14:54 UTC, dragonwu0919 commented
> Hi @dragonwu0919
> 
> We have recently upgraded the Qt version to 6.8.1, could you change the version to 6.8.1?

Surely, I can do this.

2025-01-12 23:28 UTC, yungyuc requested changes
@dragonwu0919 could you please do a rebase to remove the unnecessary merge in the PR for this simple patch?

2025-01-13 14:55 UTC, yungyuc approved these changes
> > @dragonwu0919 could you please do a rebase to remove the unnecessary merge in the PR for this simple patch?
> 
> Thank for the reminding. I forgot to squash the redundant commits.
> 
> @yungyuc could you help me review the result? Thank you.

LGTM

2025-01-13 14:55 UTC, merged