Add system make installation check
solvcon/devenv pull request #25
Opened 2021-05-09 05:35 UTC by ldotrg

Give a user a prompt when system make not install yet.

2021-05-09 05:50 UTC, yungyuc requested changes

2021-05-09 05:50 UTC, yungyuc commented on scripts/init
> +if (( $? == 1 )); then
I would like this to be fenced by an environment variable, like `$DEVENVVERBOSE` or `$DEVENVDEBUG`.  I think most of the time we would like `devenv` to be lean.

2021-05-09 07:18 UTC, tai271828 requested changes
Some coding style bike-shedding for your reference.

2021-05-09 07:18 UTC, tai271828 commented on scripts/env.d/vars
> +  echo " "
`echo " "` echo an empty space is equivalent to `echo ""`. Do you prefer which one?

2021-05-09 07:18 UTC, tai271828 commented on scripts/env.d/vars
> +  echo " Install make using the command such as ' apt install build-essential' as root and try again. "
I am not sure the leading and trailing spaces are meant to be. Besides, `' apt install build-essential'` has a leading space as well. Are they typo or on purpose?

2021-05-09 07:18 UTC, tai271828 commented on scripts/env.d/vars
> +  echo " "
ditto

2021-05-09 07:18 UTC, tai271828 commented on scripts/env.d/vars
> +fi
No newline at end of file

2021-05-10 04:35 UTC, closed without merging

2021-05-10 12:45 UTC, ldotrg reviewed
> @ldotrg It seems to me that this PR still has unfinished work and can still be worked on. Why not keep working on it?
Instead of adding the warining message and fixing the "space". 
 I will add building GNU make from source. It's better than obsessed with some spaces and learned nothing in the end.
Because these typo problem could add the .clang_format to auto fix it.